[package]
name = "dust"
version = "0.0.1"
authors = ["Hossein Noroozpour Thany Abady"]

# [dependencies]
# gtk = "*"
# cairo-rs = "*"
# glib = "*"
# gdk = "*"
# gdk-pixbuf = "*"

[dependencies.cairo-rs]
version = "*"

[dependencies.gtk]
version = "*"
features = ["v3_10"]
