[package]
name = "dust"
version = "0.0.1"
authors = ["Hossein Noroozpour Thany Abady"]

[dependencies]
conrod = { version = "*", features = ["winit", "glium"] }
find_folder = "*"
winit = "*"
glium = "*"
image = "*"
rand = "*"
